export const pair=(zh,en)=>({zh,en});
const p=pair;
export const sources={
 B:{title:'BOASt · Compartment Syndrome of the Extremities · Revised July 2025',url:'https://www.boa.ac.uk/resource/boast-10-pdf.html'},
 A:{title:'AAOS · Management of Acute Compartment Syndrome · 18 November 2025',url:'https://www.aaos.org/acscpg2025'},
 L:{title:'AO Surgery Reference · Compartment syndrome in the leg',url:'https://surgeryreference.aofoundation.org/cmf/reconstruction/further-reading/compartment-syndrome-in-the-leg'},
 T:{title:'AO Surgery Reference · Compartment syndrome in the thigh',url:'https://surgeryreference.aofoundation.org/orthopedic-trauma/adult-trauma/further-reading/compartment-syndrome-thigh'},
 F:{title:'AO Surgery Reference · Compartment syndrome in the foot',url:'https://surgeryreference.aofoundation.org/orthopedic-trauma/adult-trauma/further-reading/compartment-syndrome-foot'}
};
export const common={
 scope:p('成人急性骨筋膜室综合征 · 专业教学','Adult acute compartment syndrome · Professional education'),
 boundary:p('原创解剖关系示意，非患者分割、非按比例手术导航；切口须依据体表标志与术中直视调整。独立教学改编，非 AO / AAOS / BOA 官方产品。','Original relational anatomy schematic, not patient segmentation or scaled surgical navigation. Adapt incisions to landmarks and direct exposure. Independent teaching, not an official AO / AAOS / BOA product.'),
 decision:p('确诊后立即减压；有脉搏不能排除 ACS。诊断明确时不为测压等待。慢性运动性筋膜室综合征和儿童不属于本系列范围。','Decompress immediately once diagnosed; a pulse does not exclude ACS. Do not delay clear clinical cases for pressure testing. Chronic exertional disease and children are outside this series.'),
 params:[
  [p('压力差','Perfusion difference'),p('ΔP = 舒张压 − 室内压','ΔP = diastolic BP − compartment pressure'),p('BOASt：<30 mmHg 为风险升高；>40 mmHg 绝对室内压须考虑紧急减压。结合临床、测量趋势与资深医师判断，不能单次读数自动决定。','BOASt: <30 mmHg signals increased risk; absolute pressure >40 mmHg warrants consideration of urgent decompression. Interpret clinically with trends and senior review, not as an automatic rule.'),'B'],
  [p('重复测压','Repeated measurements'),p('AAOS：ΔP >30 mmHg','AAOS: ΔP >30 mmHg'),p('重复/持续测量可辅助排除；单次正常值不是排除证据，阈值不取代临床判断。','Repeated/continuous measurements may help rule out ACS; one normal result cannot exclude it or replace clinical judgment.'),'A'],
  [p('复评与创面计划','Reassessment & wound plan'),p('每小时 / 24 h / ≤72 h','Hourly / 24 h / ≤72 h'),p('高风险者每小时记录；筋膜切开后24小时内讨论整形修复，72小时内或病情需要时更早再探查。','Document at-risk patients hourly; discuss with plastics within 24 h and re-explore within 72 h, earlier if indicated.'),'B'],
  [p('切口长度与深度','Length & depth'),p('解剖标志 + 完整减压','Landmarks + complete release'),p('不提供通用固定厘米长度或盲切深度。所有受累室须充分减压；仅切皮肤不等于筋膜松解。','No universal length or blind cutting depth. Release every involved compartment; a skin incision is not fascial decompression.'),'A'],
 ],
 after:p('创面暂时开放；清创与肌肉活性记录后，按肿胀和组织状态安排再探查及延迟闭合/覆盖。NPWT 是可选创面处理，AAOS证据强度为有限，不是统一负压处方。','Leave wounds temporarily open; document muscle viability and debridement, then plan re-exploration and delayed closure/coverage. NPWT is an option with limited AAOS evidence, not a universal pressure prescription.'),
 late:p('迟发或漏诊并疑不可逆损害：不得按“超过某小时数”机械判断。需资深团队评估损害、肾功能和手术风险；不可逆损害时常规筋膜切开并非必然适用。','Late/missed ACS with suspected irreversible damage requires senior assessment of tissue injury, renal status and operative risk. Elapsed hours alone are not a decision rule; routine fasciotomy may be inappropriate.'),
};
export const modules={
 leg:{title:p('小腿四筋膜室切开减压','Four-compartment leg fasciotomy'),tag:p('主演示 · 双切口','PRIMARY · TWO INCISIONS'),color:'#237e75',ref:'L',
  strategy:p('双切口用于显示四室完整松解；单切口属于有经验团队的替代入路，不能据此省略深后室。','Two incisions demonstrate four-compartment release; experienced teams may use a single incision, but the deep posterior compartment must not be missed.'),
  parts:[p('前室','Anterior'),p('外侧室','Lateral'),p('深后室','Deep posterior'),p('浅后室','Superficial posterior')],
  risks:[p('腓浅神经：远端穿出深筋膜处，保护其分支。','Superficial fibular nerve: protect distal fascial exit and branches.'),p('腓总神经：腓骨颈处，近端延伸需警惕。','Common fibular nerve: vulnerable near the fibular neck.'),p('大隐静脉与隐神经：内侧皮下层。','Great saphenous vein and saphenous nerve: medial subcutaneous layer.'),p('胫后血管与胫神经：深后室，远端更表浅。','Posterior tibial vessels and tibial nerve: deep posterior, more superficial distally.'),p('胫前血管与腓深神经：前室深面。','Anterior tibial vessels and deep fibular nerve: deep in the anterior compartment.')],
  params:[[p('前外侧皮切口参照','Anterolateral landmark'),p('腓骨干前方约 2 cm','About 2 cm anterior to fibular shaft'),p('AO 描述值；依实际标志调整，并保护神经。','AO reference, adapted to actual landmarks and nerve anatomy.'),'L'],[p('后内侧皮切口参照','Posteromedial landmark'),p('胫骨后内侧缘后方约 2 cm','About 2 cm behind posteromedial tibial border'),p('不是从胫骨前嵴测量。','Not measured from the anterior tibial crest.'),'L']],
  steps:[
   [p('定位四室','Map four compartments'),p('横断面明确四室；神经血管与骨性标志先于切口。','Map compartments, neurovascular structures and bony landmarks before incisions.'),0],
   [p('规划两条皮切口','Plan two skin incisions'),p('前外侧对应前/外侧室；后内侧对应两后室。虚线只表示切皮路径。','Anterolateral reaches anterior/lateral; posteromedial reaches posterior compartments. Dashes mark skin paths only.'),1],
   [p('前室与外侧室','Anterior & lateral release'),p('辨认前肌间隔，分别松解两室筋膜；远端留意腓浅神经。','Identify the anterior intermuscular septum and release each compartment separately; protect the distal superficial fibular nerve.'),2],
   [p('两后室与比目鱼肌','Posterior release & soleus'),p('浅后室松解后仍需确认深后室；沿胫骨后缘、比目鱼肌深面辨认并松解深后筋膜。','Superficial release alone is insufficient. Identify and release deep posterior fascia along the posterior tibial border beneath soleus.'),3],
   [p('逐室检查','Verify each compartment'),p('逐一确认前、外侧、深后和浅后室已减压。神经血管结构保护不能因切口已完成而省略。','Verify anterior, lateral, deep and superficial posterior release individually, with continued neurovascular protection.'),4],
   [p('开放创面与复查','Open wound & review'),common.after,4]
  ]},
 thigh:{title:p('大腿筋膜室切开减压','Thigh compartment fasciotomy'),tag:p('独立模块 · 三筋膜室','SEPARATE MODULE · THREE COMPARTMENTS'),color:'#846149',ref:'T',
  strategy:p('前、后、内侧三室分别评估。本图按 AO 的外侧与内侧入路教学，不能将外侧皮切口等同全部三室已减压。','Assess anterior, posterior and medial compartments separately. This AO-based lateral/medial approach map does not equate one lateral skin incision with complete release.'),
  parts:[p('前室','Anterior'),p('内侧室','Medial'),p('后室','Posterior')],
  risks:[p('股动静脉：前内侧/收肌管区域。','Femoral vessels: anteromedial/adductor canal region.'),p('坐骨神经：后室深部。','Sciatic nerve: deep posterior region.'),p('股深动脉穿支：穿过外侧肌间隔。','Profunda perforators: cross the lateral intermuscular septum.'),p('隐神经与大隐静脉：内侧入路。','Saphenous nerve and great saphenous vein: medial approach.')],
  params:[[p('外侧切口轴线','Lateral axis'),p('大转子—股骨外上髁','Greater trochanter to lateral epicondyle'),p('按室的纵向范围充分暴露，不套用固定长度。','Expose the compartment length; no fixed universal length.'),'T'],[p('内侧切口参照','Medial landmark'),p('收肌结节及大收肌腱线','Adductor tubercle and magnus tendon line'),p('沿受累范围延伸，先识别血管神经。','Extend as needed after neurovascular identification.'),'T']],
  steps:[[p('识别三室','Identify three compartments'),p('前室伸肌群、内侧收肌群、后室屈肌群分别定位。','Locate anterior extensors, medial adductors and posterior flexors.'),0],[p('外侧与内侧规划','Plan lateral & medial access'),p('结合大转子、外上髁与收肌结节定位。','Use greater trochanter, lateral epicondyle and adductor tubercle landmarks.'),1],[p('阔筋膜与前室','Fascia lata & anterior'),p('纵向松解阔筋膜/髂胫束及前室筋膜。','Release fascia lata/iliotibial band and anterior fascia longitudinally.'),2],[p('后室肌间隔','Posterior septal release'),p('向前内侧牵开股外侧肌，辨认处理穿支后松解外侧肌间隔。','Retract vastus lateralis anteromedially; control perforators before septal release.'),3],[p('内侧室单独确认','Confirm medial release'),p('内侧入路保护股动静脉及隐神经静脉，确认内侧室充分减压。','Protect femoral and saphenous structures during medial release.'),4],[p('开放与再评估','Open & reassess'),common.after,4]]},
 foot:{title:p('足部筋膜室切开减压','Foot compartment fasciotomy'),tag:p('独立模块 · 方案存在争议','SEPARATE MODULE · MANAGEMENT CONTROVERSY'),color:'#67589a',ref:'F',
  strategy:p('足部管理尚无统一共识（BOASt 2025）。本页是 AO 多切口入路的解剖教学，须记录个体方案理由；足背两切口不能代表跟骨室已松解。','No consensus exists for foot management (BOASt 2025). This AO multi-incision map is anatomical teaching; document the individual plan. Two dorsal incisions do not establish calcaneal release.'),
  parts:[p('骨间室 ×4','Interossei ×4'),p('内侧室','Medial'),p('浅表室','Superficial'),p('收肌/深室','Adductor / deep'),p('外侧室','Lateral'),p('跟骨室：后足单列','Calcaneal: separate hindfoot')],
  risks:[p('足背动脉及腓深神经：足背近端/第一骨间隙附近。','Dorsalis pedis and deep fibular nerve: proximal dorsum / first interspace.'),p('足底内侧神经血管：拇展肌周围深层。','Medial plantar bundle: deep around abductor hallucis.'),p('足底外侧神经血管：深层外向走行。','Lateral plantar bundle: deep lateral course.'),p('腓神经终末皮支：足背和外侧切口周围。','Terminal fibular nerve branches: dorsal/lateral incisions.')],
  params:[[p('足背双切口轴线','Dorsal axes'),p('第 2、4 跖骨干','Second and fourth metatarsal shafts'),p('AO 入路示范；各骨间室仍需逐一确认。','AO approach example; verify each interosseous release.'),'F'],[p('内侧与外侧参照','Medial / lateral landmarks'),p('足弓拇展肌 / 第 5 跖骨跖侧','Arch at abductor hallucis / plantar to MT5'),p('跟骨室另行确认；切口数按受累范围和方案决定。','Verify calcaneal release separately; individualize access.'),'F']],
  steps:[[p('前足与后足分区','Forefoot versus hindfoot'),p('前足横断面不包含跟骨室；后足另图显示。','The forefoot section does not contain the calcaneal compartment; see the separate hindfoot inset.'),0],[p('足背双切口','Dorsal skin access'),p('第2、第4跖骨背侧轴线；保留切口之间皮桥。','Use dorsal MT2/MT4 axes and preserve the intervening skin bridge.'),1],[p('骨间与收肌室','Interossei & adductor'),p('逐一识别骨间筋膜，并通过第一骨间隙深部确认收肌室。','Identify interosseous fascia individually; assess adductor access deep in the first interspace.'),2],[p('内侧及跟骨室','Medial & calcaneal access'),p('沿拇展肌足弓入路检查内侧、浅表与跟骨相关深层，保护足底内侧束。','Use the arch/abductor hallucis approach to assess medial, superficial and calcaneal deep structures; protect the medial plantar bundle.'),3],[p('外侧与完整性','Lateral & completeness'),p('第五跖骨跖侧入路处理外侧室；按个体受累室复核，不预设所有足均相同。','A plantar-to-MT5 approach reaches the lateral compartment; verify the individual involved set.'),4],[p('创面与功能','Wound & function'),p('按软组织条件延迟闭合/覆盖，并规划踝足位置及足趾活动；方案记录须体现争议。','Plan delayed closure/coverage and ankle/toe rehabilitation, documenting the management uncertainty.'),4]]}
};
