import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {common as C,modules} from './content.js';
import cranial from './cranial.js';
import {installNV} from './neurovascular.js';
import anatomy from 'anatomy-data';
const M=({...modules,cranial})[MODULE_ID], $=s=>document.querySelector(s);
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'zh', stage=5,timer;
const t=v=>typeof v==='string'?v:v[lang], refs=ids=>ids.map(id=>`<a href="#source-${id}" data-ref="${id}">[${id}]</a>`).join(' ');
document.documentElement.style.setProperty('--accent',M.color);
document.body.innerHTML=`<header><a class="brand">TRACTION<span>ATLAS</span></a><div id="series"></div><button id="language"></button><button id="sources"></button></header><main><section class="intro"><div class="eyebrow" id="scope"></div><h1></h1><p id="subtitle"></p></section><section class="workspace"><nav id="steps"></nav><div class="viewer"><div class="view-top"><span id="reference"></span><span class="serial">${M.serial} / 03</span></div><div id="scene"><div id="labels"></div></div><div id="views"></div><div class="gesture" id="gesture"></div></div><aside><div class="eyebrow" id="stepLabel"></div><h2 id="stepTitle"></h2><p id="stepBody"></p><div class="check"><strong id="checkLabel"></strong><p id="stepCheck"></p><span id="stepRefs"></span></div><div class="controls"><button id="previous">←</button><button id="play"></button><button id="next">→</button></div><div class="settings"><label><input id="showLabels" type="checkbox" checked><span id="labelText"></span></label><label><input id="showRisk" type="checkbox" checked><span id="riskText"></span></label><label><input id="showPath" type="checkbox" checked><span id="pathText"></span></label><label id="opacityLabel"></label><input id="opacity" aria-label="Bone opacity" type="range" min="0.2" max="1" step="0.05" value="1"></div><p class="small" id="selected"></p></aside></section><section class="strategy"><div class="eyebrow" id="strategyLabel"></div><p id="strategy"></p></section><section class="downloads"><div><h2 id="exportTitle"></h2><p id="exportCaption"></p></div><button id="anatomyExport"></button><button id="constructExport"></button></section><section><h2 id="parameterTitle"></h2><p id="paramIntro"></p><div id="protocol" class="notice"></div><div class="table-scroll"><table><thead></thead><tbody></tbody></table></div></section><section><h2 id="whyTitle"></h2><div id="why" class="cards"></div></section><section class="stop"><h2 id="stopTitle"></h2><p id="stopBody"></p></section><section class="boundary"><h2 id="boundaryTitle"></h2><p id="boundaryBody"></p></section><section id="bibliography"><h2 id="sourceTitle"></h2><p id="sourceIntro"></p><ol id="sourceList"></ol></section><footer><p id="attribution"></p><p id="date"></p></footer></main><div id="toast" role="status"></div>`;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e9eee9');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#e9eee9');$('#scene').prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(32,1,1,4000), controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=180;controls.maxDistance=1800;
scene.add(new THREE.HemisphereLight(0xffffff,0x626b63,2.4));const light=new THREE.DirectionalLight(0xfff3dd,3);light.position.set(-200,400,500);scene.add(light);const rim=new THREE.DirectionalLight(0xffffff,1.4);rim.position.set(300,100,-200);scene.add(rim);
const bones=new THREE.Group(), device=new THREE.Group(),pinGroup=new THREE.Group(),risk=new THREE.Group(),path=new THREE.Group();scene.add(bones,device,pinGroup,risk,path);
const meshes=[];for(const part of anatomy.parts){let geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(part.positions,3));geo.setIndex(part.indices);geo=mergeVertices(geo,.001);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0xe2d6bd,roughness:.66,metalness:.03,side:THREE.DoubleSide}));mesh.userData.name=part.name;bones.add(mesh);meshes.push(mesh);}
const blue=new THREE.MeshStandardMaterial({color:M.color,metalness:.7,roughness:.26}), steel=new THREE.MeshStandardMaterial({color:0xd9e3e7,metalness:.8,roughness:.24});
function rod(a,b,r=2,mat=steel,group=device){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,a.distanceTo(b),20),mat);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.sub(a).normalize());group.add(mesh);return mesh;}
function ball(p,r=4,group=device,mat=blue){let x=new THREE.Mesh(new THREE.SphereGeometry(r,20,12),mat);x.position.set(...p);group.add(x);}
function curve(points,r=3){const c=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));device.add(new THREE.Mesh(new THREE.TubeGeometry(c,80,r,12,false),blue));}
function arrow(a,b,color,group){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);group.add(new THREE.ArrowHelper(b.clone().sub(a).normalize(),a,a.distanceTo(b),color,13,7));}
const leaderSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');leaderSvg.style.cssText='position:absolute;width:100%;height:100%;overflow:visible';$('#labels').append(leaderSvg);
const marks=[];function mark(p,zh,en,type='normal'){const el=document.createElement('span');el.className='annotation '+type;$('#labels').append(el);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('stroke',type==='risk'?'#b98030':'#74918b');line.setAttribute('stroke-width','1');leaderSvg.append(line);marks.push({p:new THREE.Vector3(...p),name:{zh,en},el,line,type});}
function cue(p,zh,en){ball(p,7,risk,new THREE.MeshBasicMaterial({color:0xd69236,transparent:true,opacity:.6,depthTest:false}));mark(p,zh,en,'risk');}
if(M.id==='tibial'){
 rod([-65,-7.57,4.515],[62,-7.57,4.515],2.2,steel,pinGroup);curve([[-65,-7.57,4.515],[-70,-64,29],[0,-88,38],[70,-64,29],[62,-7.57,4.515]]);ball([-65,-7.57,4.515]);ball([62,-7.57,4.515]);rod([0,-88,38],[0,-115,38],2);arrow([0,-115,38],[0,-172,38],M.color,device);arrow([82,-7.57,4.515],[-80,-7.57,4.515],0x3e91a3,path);
 mark([4,-7.57,24.5],'胫骨粗隆','Tibial tuberosity');mark([16.85,-7.57,4.515],'外侧入口 → 内侧','Lateral entry → medial');mark([-30.71,-7.57,4.515],'内侧出口','Medial exit');cue([32,-5,-19],'腓骨颈邻近风险（示意）','Fibular-neck proximity (schematic)');mark([0,-170,38],'牵引力线（示意）','Traction vector (schematic)','force');
}else if(M.id==='calcaneal'){
 rod([-56,-15,-30],[43,-15,-30],2,steel,pinGroup);curve([[-56,-15,-30],[-60,-47,-68],[-6,-67,-83],[49,-47,-68],[43,-15,-30]]);ball([-56,-15,-30]);ball([43,-15,-30]);rod([-6,-67,-83],[-6,-85,-83],2);arrow([-6,-85,-83],[-6,-137,-83],M.color,device);arrow([-85,-15,-30],[69,-15,-30],0x3e91a3,path);
 mark([-31,-14,-33],'跟骨结节','Calcaneal tuberosity');mark([-34.66,-15,-30],'内侧入口 → 外侧','Medial entry → lateral');mark([-2.43,-15,-30],'外侧出口','Lateral exit');cue([-33,14,-13],'胫后束邻近（示意）','Posterior tibial bundle proximity');cue([31,8,-25],'腓肠神经邻近（示意）','Sural nerve proximity');mark([-6,-137,-83],'牵引力线（示意）','Traction vector (schematic)','force');
}else{
 rod([-99,26,-7],[-73.6,26,-7],2.6,steel,pinGroup);rod([72.2,26,-7],[99,26,-7],2.6,steel,pinGroup);curve([[-99,26,-7],[-105,106,-7],[-64,172,-7],[0,192,-7],[64,172,-7],[105,106,-7],[99,26,-7]]);ball([-99,26,-7],5);ball([99,26,-7],5);rod([0,192,-7],[0,212,-7],2);arrow([0,212,-7],[0,270,-7],M.color,device);arrow([-125,26,-7],[-75,26,-7],0x3e91a3,path);arrow([125,26,-7],[75,26,-7],0x3e91a3,path);
 mark([-99,26,-7],'独立针点 · 非贯穿针','Separate pin · not transcranial');mark([99,26,-7],'双针牵引弓（示意）','Two-pin tong (schematic)');mark([0,-104,15],'下颈椎 · 正常参考骨骼','Subaxial spine · reference anatomy');cue([70,7,-5],'外耳道参考邻近（示意）','Ear-canal reference proximity');mark([0,268,-7],'轴向牵引（示意）','Axial traction (schematic)','force');
}
let view=1;const target=M.id==='cranial'?new THREE.Vector3(0,50,0):M.id==='calcaneal'?new THREE.Vector3(0,12,10):new THREE.Vector3(0,0,0);
function setView(i){view=i;const distance=M.id==='cranial'?960:M.id==='calcaneal'?730:800;const dirs=[[0,.12,1],M.id==='calcaneal'?[-.85,.35,-1]:[.85,.35,1],[-1,.12,.08],[0,.15,-1]];camera.position.copy(target).add(new THREE.Vector3(...dirs[i]).normalize().multiplyScalar(distance));controls.target.copy(target);controls.update();}
function resize(){const r=$('#scene').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('#scene'));setView(M.id==='cranial'?0:1);
function updateStage(){pinGroup.visible=stage>=3;device.visible=stage>=4;path.visible=stage>=2&&$('#showPath').checked;risk.visible=stage>=1&&$('#showRisk').checked;}
function ui(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=t(M.title)+' | Traction Atlas';$('h1').textContent=t(M.title);const textMap={series:C.series,scope:M.scope,subtitle:M.subtitle,reference:C.reference,gesture:C.gesture,stepLabel:C.stepLabel,checkLabel:C.check,labelText:C.labels,riskText:C.risk,pathText:C.path,opacityLabel:C.opacity,strategyLabel:C.strategy,exportTitle:C.export,exportCaption:C.caption,parameterTitle:C.parameters,paramIntro:C.paramIntro,whyTitle:C.why,stopTitle:C.stop,stopBody:M.stop,boundaryTitle:C.explanation,boundaryBody:C.boundary,sourceTitle:C.sources,sourceIntro:C.sourceIntro,attribution:C.attribution,date:C.evidenceDate,anatomyExport:C.anatomicalPlate,constructExport:C.constructPlate};for(const [id,v]of Object.entries(textMap))$('#'+id).textContent=t(v);
 $('#language').textContent=lang==='zh'?'English':'中文';$('#sources').textContent=t(C.sources);$('#selected').textContent=t(C.select);$('#play').textContent=t(timer?C.pause:C.play);$('#steps').innerHTML=`<div class="eyebrow">${t(C.steps)}</div>`+M.steps.map((s,i)=>`<button data-step="${i}" class="${stage===i?'active':''}"><span>0${i+1}</span>${t(s.title)}</button>`).join('')+`<p class="small">${t(C.noAuto)}</p>`;
 $('#stepTitle').textContent=t(M.steps[stage].title);$('#stepBody').textContent=t(M.steps[stage].body);$('#stepCheck').textContent=t(M.steps[stage].check);$('#stepRefs').innerHTML=refs(M.steps[stage].refs);$('#strategy').innerHTML=t(M.strategy)+' '+refs(M.strategyRefs);$('#views').innerHTML=C.views.map((v,i)=>`<button data-view="${i}" class="${i===view?'active':''}">${t(v)}</button>`).join('');$('#protocol').textContent=M.protocolNotice?t(M.protocolNotice):'';$('#protocol').hidden=!M.protocolNotice;
 $('thead').innerHTML='<tr>'+C.paramColumns.map(v=>`<th>${t(v)}</th>`).join('')+'</tr>';$('tbody').innerHTML=M.parameters.map(p=>`<tr><td>${t(p.name)}</td><td><strong>${t(p.value)}</strong></td><td>${t(p.scope)}</td><td>${refs(p.refs)}</td></tr>`).join('');$('#why').innerHTML=M.explanations.map(x=>`<article><h3>${t(x.title)}</h3><p>${t(x.body)}</p>${refs(x.refs)}</article>`).join('');$('#sourceList').innerHTML=M.sources.map(s=>`<li id="source-${s.id}"><a target="_blank" rel="noopener" href="${s.url}">[${s.id}] ${s.title}</a><p>${t(s.detail)}</p></li>`).join('');for(const m of marks)m.el.textContent=t(m.name);updateStage();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-step],[data-view]');if(!b)return;if(b.dataset.step!==undefined){stage=+b.dataset.step;ui();}else{setView(+b.dataset.view);ui();}});$('#language').onclick=()=>{lang=lang==='zh'?'en':'zh';ui();};$('#sources').onclick=()=>$('#bibliography').scrollIntoView({behavior:'smooth'});$('#next').onclick=()=>{stage=(stage+1)%6;ui();};$('#previous').onclick=()=>{stage=(stage+5)%6;ui();};$('#play').onclick=()=>{if(timer){clearInterval(timer);timer=null;}else{stage=0;timer=setInterval(()=>{if(stage===5){clearInterval(timer);timer=null;}else stage++;ui();},4500);}ui();};for(const id of ['showLabels','showRisk','showPath'])$('#'+id).onchange=updateStage;$('#opacity').oninput=e=>{for(const mesh of meshes){mesh.material.opacity=+e.target.value;mesh.material.transparent=+e.target.value<1;mesh.material.depthWrite=+e.target.value>.8;}};
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);let h=ray.intersectObjects(meshes)[0];if(h)$('#selected').textContent=t(C.selected)+': '+t(h.object.userData.name);});
function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera);const w=$('#scene').clientWidth,h=$('#scene').clientHeight;let occupied=[];for(const m of marks){let visible=$('#showLabels').checked&&(m.type!=='risk'||risk.visible)&&(m.type!=='force'||device.visible);m.el.style.display=m.line.style.display=visible?'block':'none';if(!visible)continue;const p=m.p.clone().project(camera);const px=(p.x+1)*w/2,py=(1-p.y)*h/2;let x=Math.max(8,Math.min(w-220,px+22)),y=Math.max(8,Math.min(h-40,py));while(occupied.some(q=>Math.abs(q[0]-x)<220&&Math.abs(q[1]-y)<40))y+=41;occupied.push([x,y]);m.el.style.transform=`translate(${x}px,${y}px)`;m.line.setAttribute('x1',px);m.line.setAttribute('y1',py);m.line.setAttribute('x2',x);m.line.setAttribute('y2',y+12);}}ui();resize();loop();
function wrap(ctx,text,x,y,maxWidth,lineHeight){let line='',lines=0;const tokens=lang==='en'?text.split(/(\s+)/):[...text];for(const ch of tokens){if(line&&ctx.measureText(line+ch).width>maxWidth){ctx.fillText(line.trim(),x,y+lines*lineHeight);line='';lines++;}line+=ch;}ctx.fillText(line.trim(),x,y+lines*lineHeight);return y+(lines+1)*lineHeight;}
async function exportPlate(kind='construct',download=true){const oldStage=stage,oldView=view;stage=kind==='anatomy'?3:5;setView(M.id==='cranial'?0:1);updateStage();const canvas=document.createElement('canvas');canvas.width=3840;canvas.height=2160;const ctx=canvas.getContext('2d');ctx.fillStyle='#f7f8f4';ctx.fillRect(0,0,3840,2160);ctx.fillStyle=M.color;ctx.fillRect(0,0,3840,20);ctx.fillStyle='#172e30';ctx.font='bold 72px Arial, sans-serif';wrap(ctx,t(M.title),130,135,3550,85);ctx.font='32px Arial, sans-serif';ctx.fillStyle='#536968';wrap(ctx,t(M.subtitle),134,230,3550,45);
 renderer.setPixelRatio(1);renderer.setSize(2200,1570,false);camera.aspect=2200/1570;camera.updateProjectionMatrix();renderer.render(scene,camera);ctx.drawImage(renderer.domElement,100,340,2200,1570);
 let labelIndex=0;for(const m of marks){if(m.type==='force'&&!device.visible)continue;const p=m.p.clone().project(camera),px=100+(p.x+1)*1100,py=340+(1-p.y)*785;const right=labelIndex%2===1,lx=right?1670:155,ly=460+Math.floor(labelIndex/2)*350;ctx.strokeStyle=m.type==='risk'?'#b98030':'#6d8b82';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(right?lx:lx+460,ly+22);ctx.stroke();ctx.fillStyle='#fffefa';ctx.fillRect(lx-10,ly-24,500,110);ctx.fillStyle=m.type==='risk'?'#895a22':M.color;ctx.font='bold 28px Arial, sans-serif';wrap(ctx,t(m.name),lx,ly+12,470,38);ctx.beginPath();ctx.arc(px,py,5,0,Math.PI*2);ctx.fill();labelIndex++;}
 ctx.font='27px Arial, sans-serif';ctx.fillStyle='#3b5150';ctx.fillText(t(C.orientation),125,1955);
 let y=390;ctx.fillStyle=M.color;ctx.font='bold 42px Arial, sans-serif';y=wrap(ctx,t(kind==='anatomy'?C.anatomicalPlate:C.constructPlate),2410,y,1250,56)+45;for(const fact of M.exportFacts){ctx.fillStyle='#1b3b3a';ctx.font='bold 35px Arial, sans-serif';y=wrap(ctx,'• '+t(fact),2410,y,1250,51)+34;}ctx.font='30px Arial, sans-serif';ctx.fillStyle='#7c452c';y=wrap(ctx,t(M.scope),2410,y+15,1230,43)+40;ctx.fillStyle='#425957';ctx.font='28px Arial, sans-serif';y=wrap(ctx,t(C.boundary),2410,y,1230,42)+30;ctx.font='24px Arial, sans-serif';wrap(ctx,M.sources.map(s=>s.id+' '+s.title).join(' · '),2410,y,1230,34);
 ctx.font='25px Arial, sans-serif';ctx.fillStyle='#546561';wrap(ctx,t(C.attribution)+' '+t(C.evidenceDate),130,2050,3550,36);const url=canvas.toDataURL('image/png');renderer.setPixelRatio(Math.min(devicePixelRatio,2));stage=oldStage;setView(oldView);resize();ui();if(download){const a=document.createElement('a');a.download=`${M.slug}-${kind}-${lang}-4k.png`;a.href=url;a.click();}return url;}
const nv=installNV({id:M.id,scene,renderer,camera,bones:meshes,host:$('#scene'),getLang:()=>lang,getTitle:()=>t(M.title),setView:i=>setView(i===0?1:M.id==='tibial'?3:2),resize});
$('#showRisk').checked=false;$('#showLabels').checked=false;updateStage();
$('#anatomyExport').onclick=()=>nv.exportPlate(0);$('#constructExport').onclick=()=>nv.exportPlate(1);window.tractionAtlas={exportPlate:(kind,download)=>nv.exportPlate(kind==='anatomy'?0:1,download),setLanguage:v=>{lang=v;ui();},setStage:v=>{stage=v;ui();},module:M.id,modelParts:meshes.length};
