import {B,S,P,step} from './content.js';
export default {id:'cranial',slug:'cranial-traction',serial:'03',color:'#67528b',title:B('颅骨牵引','Cranial traction'),subtitle:B('Gardner–Wells · 急性下颈椎关节突脱位','Gardner–Wells · acute subaxial facet dislocation'),
 scope:B('成人 C3–C7 创伤 · 脊柱专科与连续监护','Adult C3–C7 trauma · specialist care with continuous monitoring'),
 strategy:B('WFNS支持在经选择、清醒且能配合神经检查的患者中尝试闭合复位。2026 AO Spine更新强调影像与手术策略，未提出新的统一牵引重量阶梯；闭合成功也不等于韧带稳定性恢复。','WFNS supports attempted closed reduction in selected awake patients able to cooperate with neurological examination. The 2026 AO Spine recommendations address imaging and surgical strategy, not a new universal traction-loading schedule. Closed reduction does not restore ligamentous stability.'),strategyRefs:['S1','S2'],
 steps:[
  step(B('病例与基线','Selection & baseline'),B('确认下颈椎损伤形态、神经功能及检查可靠性；脊柱团队决定闭合或开放路径。','Establish injury morphology, neurological status and examination reliability; the spine team selects a closed or open pathway.'),B('枕寰脱位/颅颈分离不采用本流程；不适用于所有C1/C2损伤。','Do not use this pathway for atlanto-occipital dissociation or assume it applies to all C1/C2 injuries.'),['S1','S4']),
  step(B('准备监护环境','Prepare monitoring'),B('配置影像、生命体征监护、气道与手术升级条件；维持能报告症状的检查条件。','Arrange imaging, vital-sign monitoring, airway support and surgical escalation; retain the ability to report neurological changes.'),B('不能可靠交流者不直接套用清醒闭合复位协议；MRI及开放路径需专科判断。','Do not apply an awake-reduction protocol when reliable communication is absent; MRI and an open approach require specialist assessment.'),['S1','S4']),
  step(B('器械与双侧针点','Device & paired pin sites'),B('按具体型号IFU定位与装配；示意外耳道垂线及双侧颅骨接触点。','Use the exact device IFU for placement and assembly; the view shows an ear-canal reference line and bilateral skull contact points.'),B('两侧各一枚接触外板的针，不是贯穿头颅的横针；不能套用halo扭矩。','Two separate pins engage the outer skull table; there is no transcranial pin. Halo torque values are not interchangeable.'),['S7']),
  step(B('受控轴向牵引','Controlled axial traction'),B('牵引弓和绳路按患者影像调整；重量须来自完整、事先选定的病例协议。','Adjust the tong and rope geometry using patient imaging; loading must follow a complete, preselected clinical protocol.'),B('图中箭头仅说明轴向力，视角转动不会代表患者颈部旋转操作。','The arrow illustrates axial force only; orbiting the view is not a patient neck-rotation manoeuvre.'),['S4','S8']),
  step(B('每一级都复核','Recheck at every stage'),B('调整后再次核对神经、影像、生命体征与针点；不以“还未达到上限”为继续加重理由。','After adjustments, reassess neurological findings, imaging, vital signs and pin sites. Being below a nominal ceiling is not a reason to continue.'),B('任何神经恶化、过度分离或循环异常都应停止继续加重，立即由专科处理。','Neurological deterioration, overdistraction or circulatory change requires stopping further loading and immediate specialist action.'),['S4','S8']),
  step(B('维持与及时手术','Maintain & escalate promptly'),B('记录复位和维持状态，继续安排需要的减压与稳定；避免因持续等待牵引而耽误治疗。','Document reduction and maintenance, and proceed with indicated decompression and stabilisation without avoidable delay from continued traction.'),B('AO/Praxis 2024支持成人急性脊髓损伤24 h内早期减压作为治疗选项。','AO/Praxis 2024 recommends offering early decompression within 24 hours for adults with acute spinal cord injury.'),['S1','S3'])
 ],
 protocolNotice:B('下列重量仅解释 Pérez Rios 等2023年墨西哥城中心的成人技术协议（Table 3），不是国际统一剂量，也不是本网页的患者处方。厂家固定参数与该临床重量表分开处理。','The loads below describe the adult institutional protocol of Pérez Rios et al. (Mexico City, 2023; Table 3), not an international standard or a prescription from this page. Device fixation settings are separate from this clinical loading schedule.'),
 parameters:[
  P(B('具名协议：起始','Named protocol: initial load'),B('5 kg + C1以下每层级2.5 kg','5 kg + 2.5 kg per level below C1'),B('S8按损伤平面计算；仅作协议示例，本页不自动计算或建议使用。','S8 counts by injury level; an institutional example only, with no automatic calculation or recommendation.'),['S8']),
  P(B('具名协议：增量 / 间隔','Named protocol: increment / interval'),B('2.5 kg / 20 min','2.5 kg / 20 min'),B('保留该协议配套的连续监护、神经与影像复核；不是自动递增许可。','Requires that protocol’s monitoring and neurological / imaging reassessment; not permission to increase automatically.'),['S8']),
  P(B('具名协议：上限 / 失败','Named protocol: ceiling / failure'),B('体重50%；上限1 h未复位即终止','50% body mass; stop if unreduced after 1 h at ceiling'),B('仅S8；任何异常提前停止。不能换入其他文献60%的上限。','S8 only; abnormalities stop the process earlier. Do not substitute another report’s 60% ceiling.'),['S8']),
  P(B('具名协议：复位后','Named protocol: after reduction'),B('5 kg','5 kg'),B('仅S8报告的维持重量，不是所有患者的维持处方。','The maintenance value reported in S8, not a universal maintenance prescription.'),['S8']),
  P(B('具名协议：影像停止阈值','Named protocol: radiographic stop criterion'),B('原文：椎间隙过度分离 >5 mm','Report: interbody-space overdistraction >5 mm'),B('S8自身阈值，不是普遍安全距离；神经恶化不需等到该值。','A threshold in S8, not a generally safe distance; neurological change requires action before any threshold.'),['S8']),
  P(B('针点 / 器械固定','Pin site / device fixation'),B('外耳道垂线；颞嵴水平（该IFU）','Ear-canal vertical axis; temporal-crest level (named IFU)'),B('Medicalex D0415AH 11/2024；固定扭矩、针深及弹簧指标不可跨品牌臆定。','Medicalex D0415AH, Nov 2024; do not invent or transfer torque, depth or spring-indicator settings between devices.'),['S7']),
  P(B('减压时效','Decompression timing'),B('≤24 h：成人急性SCI','≤24 h: adult acute SCI'),B('AO/Praxis 2024早期减压建议；不是要求所有患者先完成牵引。','AO/Praxis 2024 early-decompression recommendation; does not require traction first in every patient.'),['S3'])
 ],
 explanations:[
  {title:B('MRI必须先做吗？','Must MRI always come first?'),body:B('清醒可评估患者的紧急复位前MRI时机存在差异；检查不可靠、失败或拟后路开放复位时，MRI与手术路径应重新评估。','Practice differs on MRI before urgent reduction in an awake, examinable patient. Unreliable examination, failed reduction or a planned posterior open approach warrants reassessment of MRI and the surgical pathway.'),refs:['S1','S4']},
  {title:B('这不是halo或康复牵引','Not a halo or rehabilitation protocol'),body:B('Gardner–Wells为双针牵引弓；halo环和halo-gravity矫形属于不同装置/路径，负重与扭矩不能照搬。','Gardner–Wells is a two-pin tong. Halo rings and halo-gravity deformity treatment are different devices and pathways; loads and torque settings are not interchangeable.'),refs:['S7']},
  {title:B('2026更新改变了什么？','What does the 2026 update address?'),body:B('AO Spine最新纳入的建议关注影像、非手术失败风险及固定策略；不能据此宣称某套负重阶梯已成为全球统一标准。','The included 2026 AO Spine recommendations address imaging, failure of nonoperative care and fixation strategy; they do not establish one global loading schedule.'),refs:['S2']}
 ],
 stop:B('新神经缺损、过度分离、心动过缓/低血压/心律或传导异常、针点异常及闭合失败均需停止进一步加重并升级。枕寰脱位禁用本路径；颅骨损伤或不能可靠交流者必须重新评估。','New neurological deficit, overdistraction, bradycardia/hypotension, rhythm or conduction changes, pin-site problems or failed reduction require stopping further loading and escalation. Exclude atlanto-occipital dissociation; reassess skull injury and unreliable communication.'),
 sources:[
  S('S1','WFNS — Cervical Spine Trauma Recommendations','https://wfns-spine.org/pdf/Recom-Cervical-Spine-Trauma.pdf',B('2019共识，2020发表；PDF页2、4；闭合复位与禁忌范围。','2019 consensus, published 2020; PDF pages 2 and 4; reduction pathway and exclusions.')),
  S('S2','AO Spine — Subaxial Spine Fractures (2026)','https://doi.org/10.1177/21925682261421911',B('2026-01-25上线；Global Spine J 16(3):1411–1417；影像与手术策略。','Online 25 Jan 2026; Global Spine J 16(3):1411–1417; imaging and surgical strategy.')),
  S('S3','AO Spine / Praxis — Acute SCI Guidelines (2024)','https://www.aofoundation.org/spine/clinical-library-and-tools/guidelines',B('成人急性脊髓损伤；早期减压≤24 h；强推荐，中等证据。','Adult acute SCI; early decompression ≤24 h; strong recommendation, moderate evidence.')),
  S('S4','Zileli et al. — Early Management of Cervical Spine Trauma (2020)','https://www.e-neurospine.org/upload/pdf/ns-2040282-141.pdf',B('Neurospine 17(4):710–722；闭合/开放复位与MRI时机讨论。','Neurospine 17(4):710–722; closed/open reduction and MRI timing.')),
  S('S7','Medicalex / Francemed — IFU D0415AH (11/2024)','https://medicalex.info/notices/D0415',B('英文PDF页3；仅该厂装置的定位和使用条件；不泛化至其他品牌。','English PDF page 3; placement and conditions for this manufacturer’s device only.')),
  S('S8','Pérez Rios et al. — Gardner–Wells technical note (2023)','https://pmc.ncbi.nlm.nih.gov/articles/PMC10540047/',B('Table 3及配套复核/停止规则；墨西哥城单中心协议，不是国际指南。','Table 3 and accompanying checks/stop rules; Mexico City institutional protocol, not an international guideline.'))
 ],
 exportFacts:[B('适用：经选择、清醒可评估的成人下颈椎创伤','Scope: selected awake, examinable adults with subaxial trauma'),B('每级神经 + 影像复核；异常即停止继续加重','Neurological + imaging reassessment at each stage; stop loading for change'),B('重量见S8具名协议；无通用扭矩或穿入深度','Loads: named protocol S8; no universal torque or penetration depth')]
};
